name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: appleboy/ssh-action@v1.0.0
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
          key: ${{ secrets.SSH_KEY_REMOTE }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          envs: SSH_KEY
          script: |
            IDENTITY_KEY=$(mktemp)
            echo "$SSH_KEY" >> $IDENTITY_KEY
            chmod 600 $IDENTITY_KEY
            GIT_SSH_COMMAND='ssh -i $IDENTITY_KEY -o UserKnownHostsFiles=/dev/null StrictHostKeyChecking=no' git clone git@github.com:hellojonas/barracuda.git
            cd barracuda
            ./build.sh
            rm $IDENTITY_KEY
